"""sim/baseline.add.xml, generated from junction_map.csv.

The detector definitions list the same cordon edges as junction_map.csv, and
the two were maintained separately. Remapping one counted edge after a network
rebuild updated the map and left the detectors naming the old id, so SUMO
stopped with "Unknown edge '52916461' in edgeData definition 'cnt_truck'" -
17 hours after the run was launched, because nothing was watching.

The map is the single source of the cordon. This module derives the file from
it so the two cannot drift again.

Run: uv run python -m pipeline.baseline_add
"""

import argparse
import csv
from pathlib import Path

from pipeline.common import REPO
from pipeline.cordon import PCU

JUNCTION_MAP = REPO / "sim/net/junction_map.csv"
OUT = REPO / "sim/baseline.add.xml"

HEADER = """<?xml version="1.0" encoding="UTF-8"?>
<!-- GENERATED by pipeline/baseline_add.py from sim/net/junction_map.csv.
     Do not edit: the cordon edge list lives in the map, and a hand-kept copy
     here drifted from it once already. Per-vType hourly counts on the mapped
     cordon edges; network-wide hourly meanData for D_net/T_c. Output paths are
     relative to this file (sim/), written to ../results/. -->
<additional>"""


def build(junction_map=JUNCTION_MAP, prefix="../results/baseline_"):
    edges = sorted({r["edge_id"] for r in csv.DictReader(open(junction_map))})
    joined = " ".join(edges)
    lines = [HEADER]
    for vtype in PCU:
        lines.append(
            f'    <edgeData id="cnt_{vtype}" file="{prefix}edgedata_{vtype}.xml" '
            f'period="3600" vTypes="{vtype}" edges="{joined}"/>')
    lines.append(
        f'    <edgeData id="net_hourly" file="{prefix}edgedata_net.xml" '
        'period="3600" excludeEmpty="true"/>')
    lines.append("</additional>")
    return "\n".join(lines) + "\n", len(edges)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--junction-map", type=Path, default=JUNCTION_MAP)
    ap.add_argument("-o", "--out", type=Path, default=OUT)
    args = ap.parse_args()
    body, n = build(args.junction_map)
    args.out.write_text(body)
    print(f"{args.out}: {n} cordon edges from {args.junction_map.name}")


if __name__ == "__main__":
    main()
