"""Resolve the A10 signal patch against whatever the current network calls its
junctions.

sim/net/tls-patch.nod.xml names the police-metered study junctions so
netconvert can make them actuated signals. It names them by node id, and
netconvert's junction ids are not stable: --junctions.join merges nodes into
`cluster_<id>_<id>_...` names that depend on the geometry, so a change
elsewhere in the build renames them. Deriving lane counts from carriageway
width merged the two Shahid Gate nodes into one cluster, netconvert stopped
with "Missing position (at node ID='6540538696')", and the rebuild died.

Cluster names carry their member ids, so a patch entry can be matched to the
current network by membership instead of by exact name. This module rewrites
the patch to the current names and fails loudly on an entry it cannot place -
a signal that silently vanishes is a capacity change nobody sees.

Run: uv run python -m pipeline.tls_patch -n <net> -o <resolved patch>
"""

import argparse
import re
from pathlib import Path
from xml.etree import ElementTree as ET

from pipeline.common import REPO

PATCH = REPO / "sim/net/tls-patch.nod.xml"
RESOLVED = REPO / "sim/net/tls-patch-resolved.nod.xml"


def members(node_id):
    """The original node ids a (possibly clustered) junction id stands for.

    'cluster_a_b_#1more' keeps the ids it lists; the '#Nmore' suffix means
    netconvert truncated the name, so membership is a subset and matching has
    to tolerate that."""
    if not node_id.startswith("cluster_"):
        return {node_id}
    return {p for p in node_id[len("cluster_"):].split("_") if p.isdigit()}


def resolve(patch_ids, net):
    """[(patch_id, [current ids])] - a patch entry may land on several nodes if
    the network split what used to be one junction."""
    index = [(n.getID(), members(n.getID())) for n in net.getNodes()]
    out = []
    for pid in patch_ids:
        want = members(pid)
        hits = [nid for nid, have in index if have & want]
        out.append((pid, sorted(hits)))
    return out


def rewrite(net, patch=PATCH, out=RESOLVED):
    import sumolib

    if not hasattr(net, "getNode"):
        net = sumolib.net.readNet(str(net))
    tree = ET.parse(patch)
    root = tree.getroot()
    entries = [(e.get("id"), dict(e.attrib)) for e in root.findall("node")]
    resolved, missing, seen = [], [], set()
    for (pid, attrs), (_, hits) in zip(entries, resolve([p for p, _ in entries], net)):
        if not hits:
            missing.append(pid)
            continue
        for nid in hits:
            if nid in seen:
                continue
            seen.add(nid)
            resolved.append({**attrs, "id": nid})
    if missing:
        raise SystemExit(
            f"tls patch: cannot place {len(missing)} junction(s) in this "
            f"network: {missing}. A signalled junction that disappears is a "
            "capacity change; fix the patch rather than dropping it.")

    lines = ['<!-- Generated by pipeline/tls_patch.py from sim/net/tls-patch.nod.xml.',
             '     Junction ids are resolved against the current network: netconvert',
             '     renames joined junctions, so the patch is matched by cluster',
             '     membership. Edit the source patch, not this file. -->',
             "<nodes>"]
    for attrs in resolved:
        lines.append("    <node " + " ".join(
            f'{k}="{v}"' for k, v in attrs.items()) + "/>")
    lines.append("</nodes>")
    Path(out).write_text("\n".join(lines) + "\n")
    return {"entries": len(entries), "nodes": len(resolved)}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("-n", "--net", default=REPO / "sim/net/corridor-filtered.net.xml")
    ap.add_argument("--patch", type=Path, default=PATCH)
    ap.add_argument("-o", "--out", type=Path, default=RESOLVED)
    args = ap.parse_args()
    stats = rewrite(args.net, args.patch, args.out)
    print(f"{args.out}: {stats['entries']} patch entries -> "
          f"{stats['nodes']} junctions in this network")


if __name__ == "__main__":
    main()
